codium --install-extension 4ops.terraform
codium --install-extension ahmadalli.vscode-nginx-conf
codium --install-extension bmewburn.vscode-intelephense-client
codium --install-extension christian-kohler.npm-intellisense
codium --install-extension dcasella.monokai-plusplus
codium --install-extension dsznajder.es7-react-js-snippets
codium --install-extension eamodio.gitlens
codium --install-extension EditorConfig.EditorConfig
codium --install-extension foxundermoon.shell-format
codium --install-extension golang.go
codium --install-extension HookyQR.beautify
codium --install-extension ms-azuretools.vscode-docker
codium --install-extension ms-pyright.pyright
codium --install-extension ms-python.python
codium --install-extension ms-vscode.live-server
codium --install-extension ms-vscode.sublime-keybindings
codium --install-extension mtxr.sqltools
codium --install-extension njpwerner.autodocstring
codium --install-extension PKief.material-icon-theme
codium --install-extension redhat.ansible
codium --install-extension redhat.vscode-yaml
codium --install-extension robole.file-bunny
codium --install-extension sourcery.sourcery
codium --install-extension vscodevim.vim
codium --install-extension xabikos.JavaScriptSnippets
codium --install-extension yzhang.markdown-all-in-one
