codium --install-extension 4ops.terraform
codium --install-extension ahmadalli.vscode-nginx-conf
codium --install-extension bmewburn.vscode-intelephense-client
codium --install-extension bradlc.vscode-tailwindcss
codium --install-extension christian-kohler.npm-intellisense
codium --install-extension dsznajder.es7-react-js-snippets
codium --install-extension eamodio.gitlens
codium --install-extension EditorConfig.EditorConfig
codium --install-extension esbenp.prettier-vscode
codium --install-extension foxundermoon.shell-format
codium --install-extension HansUXdev.bootstrap5-snippets
codium --install-extension ms-azuretools.vscode-docker
codium --install-extension ms-pyright.pyright
codium --install-extension ms-python.python
codium --install-extension mtxr.sqltools
codium --install-extension njpwerner.autodocstring
codium --install-extension PKief.material-icon-theme
codium --install-extension redhat.vscode-yaml
codium --install-extension ritwickdey.LiveServer
codium --install-extension robole.file-bunny
codium --install-extension rust-lang.rust-analyzer
codium --install-extension serayuzgur.crates
codium --install-extension sourcery.sourcery
codium --install-extension Tomi.xasnippets
codium --install-extension vadimcn.vscode-lldb
codium --install-extension vscodevim.vim
